/**
 * Generated by Scrooge
 *   version: 18.10.0
 *   rev: dda071e1412b53f4bfdebc19e474f584e475d475
 *   built at: 20181018-174244
 */
package modeldb

import com.twitter.io.Buf
import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil,
  ValidatingThriftStruct,
  ValidatingThriftStructCodec3
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object ExperimentEvent extends ValidatingThriftStructCodec3[ExperimentEvent] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct: TStruct = new TStruct("ExperimentEvent")
  val ExperimentField: TField = new TField("experiment", TType.STRUCT, 1)
  val ExperimentFieldManifest: Manifest[modeldb.Experiment] = implicitly[Manifest[modeldb.Experiment]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      ExperimentField,
      false,
      false,
      ExperimentFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: ExperimentEvent): Unit = {
  }

  /**
   * Checks that the struct is a valid as a new instance. If there are any missing required or
   * construction required fields, return a non-empty list.
   */
  def validateNewInstance(item: ExperimentEvent): scala.Seq[com.twitter.scrooge.validation.Issue] = {
    val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

    buf ++= validateField(item.experiment)
    buf.toList
  }

  def withoutPassthroughFields(original: ExperimentEvent): ExperimentEvent =
    new Immutable(
      experiment =
        {
          val field = original.experiment
          modeldb.Experiment.withoutPassthroughFields(field)
        }
    )

  override def encode(_item: ExperimentEvent, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): ExperimentEvent = {

    var experiment: modeldb.Experiment = null

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                experiment = readExperimentValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'experiment' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      experiment,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): ExperimentEvent =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[modeldb] def eagerDecode(_iprot: TProtocol): ExperimentEvent = {
    var experiment: modeldb.Experiment = null
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRUCT =>
                experiment = readExperimentValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'experiment' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      experiment,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    experiment: modeldb.Experiment
  ): ExperimentEvent =
    new Immutable(
      experiment
    )

  def unapply(_item: ExperimentEvent): _root_.scala.Option[modeldb.Experiment] = _root_.scala.Some(_item.experiment)


  @inline private[modeldb] def readExperimentValue(_iprot: TProtocol): modeldb.Experiment = {
    modeldb.Experiment.decode(_iprot)
  }

  @inline private def writeExperimentField(experiment_item: modeldb.Experiment, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ExperimentField)
    writeExperimentValue(experiment_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExperimentValue(experiment_item: modeldb.Experiment, _oprot: TProtocol): Unit = {
    experiment_item.write(_oprot)
  }


  object Immutable extends ThriftStructCodec3[ExperimentEvent] {
    override def encode(_item: ExperimentEvent, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): ExperimentEvent = ExperimentEvent.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[ExperimentEvent] = ExperimentEvent.metaData
  }

  /**
   * The default read-only implementation of ExperimentEvent.  You typically should not need to
   * directly reference this class; instead, use the ExperimentEvent.apply method to construct
   * new instances.
   */
  class Immutable(
      val experiment: modeldb.Experiment,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ExperimentEvent {
    def this(
      experiment: modeldb.Experiment
    ) = this(
      experiment,
      Map.empty[Short, TFieldBlob]
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val experiment: modeldb.Experiment,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ExperimentEvent {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the ExperimentEvent trait with additional state or
   * behavior and implement the read-only methods from ExperimentEvent using an underlying
   * instance.
   */
  trait Proxy extends ExperimentEvent {
    protected def _underlying_ExperimentEvent: ExperimentEvent
    override def experiment: modeldb.Experiment = _underlying_ExperimentEvent.experiment
    override def _passthroughFields: immutable$Map[Short, TFieldBlob] = _underlying_ExperimentEvent._passthroughFields
  }
}

/**
 * Prefer the companion object's [[modeldb.ExperimentEvent.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait ExperimentEvent
  extends ThriftStruct
  with _root_.scala.Product1[modeldb.Experiment]
  with ValidatingThriftStruct[ExperimentEvent]
  with java.io.Serializable
{
  import ExperimentEvent._

  def experiment: modeldb.Experiment

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1: modeldb.Experiment = experiment


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (experiment ne null) {
                writeExperimentValue(experiment, _oprot)
                _root_.scala.Some(ExperimentEvent.ExperimentField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): ExperimentEvent = {
    var experiment: modeldb.Experiment = this.experiment
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        experiment = readExperimentValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      experiment,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): ExperimentEvent = {
    var experiment: modeldb.Experiment = this.experiment

    _fieldId match {
      case 1 =>
        experiment = null
      case _ =>
    }
    new Immutable(
      experiment,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetExperiment: ExperimentEvent = unsetField(1)


  override def write(_oprot: TProtocol): Unit = {
    ExperimentEvent.validate(this)
    _oprot.writeStructBegin(Struct)
    if (experiment ne null) writeExperimentField(experiment, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    experiment: modeldb.Experiment = this.experiment,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): ExperimentEvent =
    new Immutable(
      experiment,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[ExperimentEvent]

  private def _equals(x: ExperimentEvent, y: ExperimentEvent): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator) &&
      x._passthroughFields == y._passthroughFields

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[ExperimentEvent])

  override def hashCode: Int = {
    var hash = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    hash
  }

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.experiment
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "ExperimentEvent"

  def _codec: ValidatingThriftStructCodec3[ExperimentEvent] = ExperimentEvent
}

