/**
 * Generated by Scrooge
 *   version: 18.10.0
 *   rev: dda071e1412b53f4bfdebc19e474f584e475d475
 *   built at: 20181018-174244
 */
package modeldb

import com.twitter.io.Buf
import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil,
  ValidatingThriftStruct,
  ValidatingThriftStructCodec3
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object MetricEventResponse extends ValidatingThriftStructCodec3[MetricEventResponse] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct: TStruct = new TStruct("MetricEventResponse")
  val ModelIdField: TField = new TField("modelId", TType.I32, 1)
  val ModelIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]
  val DfIdField: TField = new TField("dfId", TType.I32, 2)
  val DfIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]
  val EventIdField: TField = new TField("eventId", TType.I32, 3)
  val EventIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]
  val MetricEventIdField: TField = new TField("metricEventId", TType.I32, 4)
  val MetricEventIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      ModelIdField,
      false,
      false,
      ModelIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      DfIdField,
      false,
      false,
      DfIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      EventIdField,
      false,
      false,
      EventIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      MetricEventIdField,
      false,
      false,
      MetricEventIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: MetricEventResponse): Unit = {
  }

  /**
   * Checks that the struct is a valid as a new instance. If there are any missing required or
   * construction required fields, return a non-empty list.
   */
  def validateNewInstance(item: MetricEventResponse): scala.Seq[com.twitter.scrooge.validation.Issue] = {
    val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

    buf ++= validateField(item.modelId)
    buf ++= validateField(item.dfId)
    buf ++= validateField(item.eventId)
    buf ++= validateField(item.metricEventId)
    buf.toList
  }

  def withoutPassthroughFields(original: MetricEventResponse): MetricEventResponse =
    new Immutable(
      modelId =
        {
          val field = original.modelId
          field
        },
      dfId =
        {
          val field = original.dfId
          field
        },
      eventId =
        {
          val field = original.eventId
          field
        },
      metricEventId =
        {
          val field = original.metricEventId
          field
        }
    )

  override def encode(_item: MetricEventResponse, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): MetricEventResponse = {

    var modelId: Int = 0
    var dfId: Int = 0
    var eventId: Int = 0
    var metricEventId: Int = 0

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                modelId = readModelIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'modelId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 =>
    
                dfId = readDfIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'dfId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
    
                eventId = readEventIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'eventId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I32 =>
    
                metricEventId = readMetricEventIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'metricEventId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      modelId,
      dfId,
      eventId,
      metricEventId,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): MetricEventResponse =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[modeldb] def eagerDecode(_iprot: TProtocol): MetricEventResponse = {
    var modelId: Int = 0
    var dfId: Int = 0
    var eventId: Int = 0
    var metricEventId: Int = 0
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                modelId = readModelIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'modelId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 =>
                dfId = readDfIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'dfId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
                eventId = readEventIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'eventId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I32 =>
                metricEventId = readMetricEventIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'metricEventId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      modelId,
      dfId,
      eventId,
      metricEventId,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    modelId: Int,
    dfId: Int,
    eventId: Int,
    metricEventId: Int
  ): MetricEventResponse =
    new Immutable(
      modelId,
      dfId,
      eventId,
      metricEventId
    )

  def unapply(_item: MetricEventResponse): _root_.scala.Option[_root_.scala.Tuple4[Int, Int, Int, Int]] = _root_.scala.Some(_item.toTuple)


  @inline private[modeldb] def readModelIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeModelIdField(modelId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ModelIdField)
    writeModelIdValue(modelId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeModelIdValue(modelId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(modelId_item)
  }

  @inline private[modeldb] def readDfIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeDfIdField(dfId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DfIdField)
    writeDfIdValue(dfId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDfIdValue(dfId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(dfId_item)
  }

  @inline private[modeldb] def readEventIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeEventIdField(eventId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(EventIdField)
    writeEventIdValue(eventId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeEventIdValue(eventId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(eventId_item)
  }

  @inline private[modeldb] def readMetricEventIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeMetricEventIdField(metricEventId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(MetricEventIdField)
    writeMetricEventIdValue(metricEventId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeMetricEventIdValue(metricEventId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(metricEventId_item)
  }


  object Immutable extends ThriftStructCodec3[MetricEventResponse] {
    override def encode(_item: MetricEventResponse, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): MetricEventResponse = MetricEventResponse.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[MetricEventResponse] = MetricEventResponse.metaData
  }

  /**
   * The default read-only implementation of MetricEventResponse.  You typically should not need to
   * directly reference this class; instead, use the MetricEventResponse.apply method to construct
   * new instances.
   */
  class Immutable(
      val modelId: Int,
      val dfId: Int,
      val eventId: Int,
      val metricEventId: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends MetricEventResponse {
    def this(
      modelId: Int,
      dfId: Int,
      eventId: Int,
      metricEventId: Int
    ) = this(
      modelId,
      dfId,
      eventId,
      metricEventId,
      Map.empty[Short, TFieldBlob]
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val modelId: Int,
      val dfId: Int,
      val eventId: Int,
      val metricEventId: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends MetricEventResponse {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the MetricEventResponse trait with additional state or
   * behavior and implement the read-only methods from MetricEventResponse using an underlying
   * instance.
   */
  trait Proxy extends MetricEventResponse {
    protected def _underlying_MetricEventResponse: MetricEventResponse
    override def modelId: Int = _underlying_MetricEventResponse.modelId
    override def dfId: Int = _underlying_MetricEventResponse.dfId
    override def eventId: Int = _underlying_MetricEventResponse.eventId
    override def metricEventId: Int = _underlying_MetricEventResponse.metricEventId
    override def _passthroughFields: immutable$Map[Short, TFieldBlob] = _underlying_MetricEventResponse._passthroughFields
  }
}

/**
 * Prefer the companion object's [[modeldb.MetricEventResponse.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait MetricEventResponse
  extends ThriftStruct
  with _root_.scala.Product4[Int, Int, Int, Int]
  with ValidatingThriftStruct[MetricEventResponse]
  with java.io.Serializable
{
  import MetricEventResponse._

  def modelId: Int
  def dfId: Int
  def eventId: Int
  def metricEventId: Int

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1: Int = modelId
  def _2: Int = dfId
  def _3: Int = eventId
  def _4: Int = metricEventId

  def toTuple: _root_.scala.Tuple4[Int, Int, Int, Int] = {
    (
      modelId,
      dfId,
      eventId,
      metricEventId
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeModelIdValue(modelId, _oprot)
                _root_.scala.Some(MetricEventResponse.ModelIdField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (true) {
                writeDfIdValue(dfId, _oprot)
                _root_.scala.Some(MetricEventResponse.DfIdField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (true) {
                writeEventIdValue(eventId, _oprot)
                _root_.scala.Some(MetricEventResponse.EventIdField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (true) {
                writeMetricEventIdValue(metricEventId, _oprot)
                _root_.scala.Some(MetricEventResponse.MetricEventIdField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): MetricEventResponse = {
    var modelId: Int = this.modelId
    var dfId: Int = this.dfId
    var eventId: Int = this.eventId
    var metricEventId: Int = this.metricEventId
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        modelId = readModelIdValue(_blob.read)
      case 2 =>
        dfId = readDfIdValue(_blob.read)
      case 3 =>
        eventId = readEventIdValue(_blob.read)
      case 4 =>
        metricEventId = readMetricEventIdValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      modelId,
      dfId,
      eventId,
      metricEventId,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): MetricEventResponse = {
    var modelId: Int = this.modelId
    var dfId: Int = this.dfId
    var eventId: Int = this.eventId
    var metricEventId: Int = this.metricEventId

    _fieldId match {
      case 1 =>
        modelId = 0
      case 2 =>
        dfId = 0
      case 3 =>
        eventId = 0
      case 4 =>
        metricEventId = 0
      case _ =>
    }
    new Immutable(
      modelId,
      dfId,
      eventId,
      metricEventId,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetModelId: MetricEventResponse = unsetField(1)

  def unsetDfId: MetricEventResponse = unsetField(2)

  def unsetEventId: MetricEventResponse = unsetField(3)

  def unsetMetricEventId: MetricEventResponse = unsetField(4)


  override def write(_oprot: TProtocol): Unit = {
    MetricEventResponse.validate(this)
    _oprot.writeStructBegin(Struct)
    writeModelIdField(modelId, _oprot)
    writeDfIdField(dfId, _oprot)
    writeEventIdField(eventId, _oprot)
    writeMetricEventIdField(metricEventId, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    modelId: Int = this.modelId,
    dfId: Int = this.dfId,
    eventId: Int = this.eventId,
    metricEventId: Int = this.metricEventId,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): MetricEventResponse =
    new Immutable(
      modelId,
      dfId,
      eventId,
      metricEventId,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[MetricEventResponse]

  private def _equals(x: MetricEventResponse, y: MetricEventResponse): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator) &&
      x._passthroughFields == y._passthroughFields

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[MetricEventResponse])

  override def hashCode: Int = {
    var hash = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    hash
  }

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 4

  override def productElement(n: Int): Any = n match {
    case 0 => this.modelId
    case 1 => this.dfId
    case 2 => this.eventId
    case 3 => this.metricEventId
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "MetricEventResponse"

  def _codec: ValidatingThriftStructCodec3[MetricEventResponse] = MetricEventResponse
}

