/**
 * Generated by Scrooge
 *   version: 18.10.0
 *   rev: dda071e1412b53f4bfdebc19e474f584e475d475
 *   built at: 20181018-174244
 */
package modeldb

import com.twitter.io.Buf
import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil,
  ValidatingThriftStruct,
  ValidatingThriftStructCodec3
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object ProjectExperimentsAndRuns extends ValidatingThriftStructCodec3[ProjectExperimentsAndRuns] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct: TStruct = new TStruct("ProjectExperimentsAndRuns")
  val ProjIdField: TField = new TField("projId", TType.I32, 1)
  val ProjIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]
  val ExperimentsField: TField = new TField("experiments", TType.LIST, 2)
  val ExperimentsFieldManifest: Manifest[Seq[modeldb.Experiment]] = implicitly[Manifest[Seq[modeldb.Experiment]]]
  val ExperimentRunsField: TField = new TField("experimentRuns", TType.LIST, 3)
  val ExperimentRunsFieldManifest: Manifest[Seq[modeldb.ExperimentRun]] = implicitly[Manifest[Seq[modeldb.ExperimentRun]]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      ProjIdField,
      false,
      false,
      ProjIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      ExperimentsField,
      false,
      false,
      ExperimentsFieldManifest,
      _root_.scala.None,
      _root_.scala.Some(implicitly[Manifest[modeldb.Experiment]]),
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      ExperimentRunsField,
      false,
      false,
      ExperimentRunsFieldManifest,
      _root_.scala.None,
      _root_.scala.Some(implicitly[Manifest[modeldb.ExperimentRun]]),
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: ProjectExperimentsAndRuns): Unit = {
  }

  /**
   * Checks that the struct is a valid as a new instance. If there are any missing required or
   * construction required fields, return a non-empty list.
   */
  def validateNewInstance(item: ProjectExperimentsAndRuns): scala.Seq[com.twitter.scrooge.validation.Issue] = {
    val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

    buf ++= validateField(item.projId)
    buf ++= validateField(item.experiments)
    buf ++= validateField(item.experimentRuns)
    buf.toList
  }

  def withoutPassthroughFields(original: ProjectExperimentsAndRuns): ProjectExperimentsAndRuns =
    new Immutable(
      projId =
        {
          val field = original.projId
          field
        },
      experiments =
        {
          val field = original.experiments
          field.map { field =>
            modeldb.Experiment.withoutPassthroughFields(field)
          }
        },
      experimentRuns =
        {
          val field = original.experimentRuns
          field.map { field =>
            modeldb.ExperimentRun.withoutPassthroughFields(field)
          }
        }
    )

  override def encode(_item: ProjectExperimentsAndRuns, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): ProjectExperimentsAndRuns = {

    var projId: Int = 0
    var experiments: Seq[modeldb.Experiment] = Seq[modeldb.Experiment]()
    var experimentRuns: Seq[modeldb.ExperimentRun] = Seq[modeldb.ExperimentRun]()

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                projId = readProjIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'projId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.LIST =>
    
                experiments = readExperimentsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.LIST
                throw new TProtocolException(
                  "Received wrong type for field 'experiments' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.LIST =>
    
                experimentRuns = readExperimentRunsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.LIST
                throw new TProtocolException(
                  "Received wrong type for field 'experimentRuns' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      projId,
      experiments,
      experimentRuns,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): ProjectExperimentsAndRuns =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[modeldb] def eagerDecode(_iprot: TProtocol): ProjectExperimentsAndRuns = {
    var projId: Int = 0
    var experiments: Seq[modeldb.Experiment] = Seq[modeldb.Experiment]()
    var experimentRuns: Seq[modeldb.ExperimentRun] = Seq[modeldb.ExperimentRun]()
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                projId = readProjIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'projId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.LIST =>
                experiments = readExperimentsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.LIST
                throw new TProtocolException(
                  "Received wrong type for field 'experiments' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.LIST =>
                experimentRuns = readExperimentRunsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.LIST
                throw new TProtocolException(
                  "Received wrong type for field 'experimentRuns' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      projId,
      experiments,
      experimentRuns,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    projId: Int,
    experiments: Seq[modeldb.Experiment] = Seq[modeldb.Experiment](),
    experimentRuns: Seq[modeldb.ExperimentRun] = Seq[modeldb.ExperimentRun]()
  ): ProjectExperimentsAndRuns =
    new Immutable(
      projId,
      experiments,
      experimentRuns
    )

  def unapply(_item: ProjectExperimentsAndRuns): _root_.scala.Option[_root_.scala.Tuple3[Int, Seq[modeldb.Experiment], Seq[modeldb.ExperimentRun]]] = _root_.scala.Some(_item.toTuple)


  @inline private[modeldb] def readProjIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeProjIdField(projId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ProjIdField)
    writeProjIdValue(projId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeProjIdValue(projId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(projId_item)
  }

  @inline private[modeldb] def readExperimentsValue(_iprot: TProtocol): Seq[modeldb.Experiment] = {
    val _list = _iprot.readListBegin()
    if (_list.size == 0) {
      _iprot.readListEnd()
      Nil
    } else {
      val _rv = new mutable$ArrayBuffer[modeldb.Experiment](_list.size)
      var _i = 0
      while (_i < _list.size) {
        _rv += {
          modeldb.Experiment.decode(_iprot)
        }
        _i += 1
      }
      _iprot.readListEnd()
      _rv
    }
  }

  @inline private def writeExperimentsField(experiments_item: Seq[modeldb.Experiment], _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ExperimentsField)
    writeExperimentsValue(experiments_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExperimentsValue(experiments_item: Seq[modeldb.Experiment], _oprot: TProtocol): Unit = {
    _oprot.writeListBegin(new TList(TType.STRUCT, experiments_item.size))
    experiments_item match {
      case _: IndexedSeq[_] =>
        var _i = 0
        val _size = experiments_item.size
        while (_i < _size) {
          val experiments_item_element = experiments_item(_i)
          experiments_item_element.write(_oprot)
          _i += 1
        }
      case _ =>
        experiments_item.foreach { experiments_item_element =>
          experiments_item_element.write(_oprot)
        }
    }
    _oprot.writeListEnd()
  }

  @inline private[modeldb] def readExperimentRunsValue(_iprot: TProtocol): Seq[modeldb.ExperimentRun] = {
    val _list = _iprot.readListBegin()
    if (_list.size == 0) {
      _iprot.readListEnd()
      Nil
    } else {
      val _rv = new mutable$ArrayBuffer[modeldb.ExperimentRun](_list.size)
      var _i = 0
      while (_i < _list.size) {
        _rv += {
          modeldb.ExperimentRun.decode(_iprot)
        }
        _i += 1
      }
      _iprot.readListEnd()
      _rv
    }
  }

  @inline private def writeExperimentRunsField(experimentRuns_item: Seq[modeldb.ExperimentRun], _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ExperimentRunsField)
    writeExperimentRunsValue(experimentRuns_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeExperimentRunsValue(experimentRuns_item: Seq[modeldb.ExperimentRun], _oprot: TProtocol): Unit = {
    _oprot.writeListBegin(new TList(TType.STRUCT, experimentRuns_item.size))
    experimentRuns_item match {
      case _: IndexedSeq[_] =>
        var _i = 0
        val _size = experimentRuns_item.size
        while (_i < _size) {
          val experimentRuns_item_element = experimentRuns_item(_i)
          experimentRuns_item_element.write(_oprot)
          _i += 1
        }
      case _ =>
        experimentRuns_item.foreach { experimentRuns_item_element =>
          experimentRuns_item_element.write(_oprot)
        }
    }
    _oprot.writeListEnd()
  }


  object Immutable extends ThriftStructCodec3[ProjectExperimentsAndRuns] {
    override def encode(_item: ProjectExperimentsAndRuns, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): ProjectExperimentsAndRuns = ProjectExperimentsAndRuns.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[ProjectExperimentsAndRuns] = ProjectExperimentsAndRuns.metaData
  }

  /**
   * The default read-only implementation of ProjectExperimentsAndRuns.  You typically should not need to
   * directly reference this class; instead, use the ProjectExperimentsAndRuns.apply method to construct
   * new instances.
   */
  class Immutable(
      val projId: Int,
      val experiments: Seq[modeldb.Experiment],
      val experimentRuns: Seq[modeldb.ExperimentRun],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ProjectExperimentsAndRuns {
    def this(
      projId: Int,
      experiments: Seq[modeldb.Experiment] = Seq[modeldb.Experiment](),
      experimentRuns: Seq[modeldb.ExperimentRun] = Seq[modeldb.ExperimentRun]()
    ) = this(
      projId,
      experiments,
      experimentRuns,
      Map.empty[Short, TFieldBlob]
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val projId: Int,
      val experiments: Seq[modeldb.Experiment],
      val experimentRuns: Seq[modeldb.ExperimentRun],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends ProjectExperimentsAndRuns {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the ProjectExperimentsAndRuns trait with additional state or
   * behavior and implement the read-only methods from ProjectExperimentsAndRuns using an underlying
   * instance.
   */
  trait Proxy extends ProjectExperimentsAndRuns {
    protected def _underlying_ProjectExperimentsAndRuns: ProjectExperimentsAndRuns
    override def projId: Int = _underlying_ProjectExperimentsAndRuns.projId
    override def experiments: Seq[modeldb.Experiment] = _underlying_ProjectExperimentsAndRuns.experiments
    override def experimentRuns: Seq[modeldb.ExperimentRun] = _underlying_ProjectExperimentsAndRuns.experimentRuns
    override def _passthroughFields: immutable$Map[Short, TFieldBlob] = _underlying_ProjectExperimentsAndRuns._passthroughFields
  }
}

/**
 * Prefer the companion object's [[modeldb.ProjectExperimentsAndRuns.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait ProjectExperimentsAndRuns
  extends ThriftStruct
  with _root_.scala.Product3[Int, Seq[modeldb.Experiment], Seq[modeldb.ExperimentRun]]
  with ValidatingThriftStruct[ProjectExperimentsAndRuns]
  with java.io.Serializable
{
  import ProjectExperimentsAndRuns._

  def projId: Int
  def experiments: Seq[modeldb.Experiment]
  def experimentRuns: Seq[modeldb.ExperimentRun]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1: Int = projId
  def _2: Seq[modeldb.Experiment] = experiments
  def _3: Seq[modeldb.ExperimentRun] = experimentRuns

  def toTuple: _root_.scala.Tuple3[Int, Seq[modeldb.Experiment], Seq[modeldb.ExperimentRun]] = {
    (
      projId,
      experiments,
      experimentRuns
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeProjIdValue(projId, _oprot)
                _root_.scala.Some(ProjectExperimentsAndRuns.ProjIdField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (experiments ne null) {
                writeExperimentsValue(experiments, _oprot)
                _root_.scala.Some(ProjectExperimentsAndRuns.ExperimentsField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (experimentRuns ne null) {
                writeExperimentRunsValue(experimentRuns, _oprot)
                _root_.scala.Some(ProjectExperimentsAndRuns.ExperimentRunsField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): ProjectExperimentsAndRuns = {
    var projId: Int = this.projId
    var experiments: Seq[modeldb.Experiment] = this.experiments
    var experimentRuns: Seq[modeldb.ExperimentRun] = this.experimentRuns
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        projId = readProjIdValue(_blob.read)
      case 2 =>
        experiments = readExperimentsValue(_blob.read)
      case 3 =>
        experimentRuns = readExperimentRunsValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      projId,
      experiments,
      experimentRuns,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): ProjectExperimentsAndRuns = {
    var projId: Int = this.projId
    var experiments: Seq[modeldb.Experiment] = this.experiments
    var experimentRuns: Seq[modeldb.ExperimentRun] = this.experimentRuns

    _fieldId match {
      case 1 =>
        projId = 0
      case 2 =>
        experiments = Seq[modeldb.Experiment]()
      case 3 =>
        experimentRuns = Seq[modeldb.ExperimentRun]()
      case _ =>
    }
    new Immutable(
      projId,
      experiments,
      experimentRuns,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetProjId: ProjectExperimentsAndRuns = unsetField(1)

  def unsetExperiments: ProjectExperimentsAndRuns = unsetField(2)

  def unsetExperimentRuns: ProjectExperimentsAndRuns = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    ProjectExperimentsAndRuns.validate(this)
    _oprot.writeStructBegin(Struct)
    writeProjIdField(projId, _oprot)
    if (experiments ne null) writeExperimentsField(experiments, _oprot)
    if (experimentRuns ne null) writeExperimentRunsField(experimentRuns, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    projId: Int = this.projId,
    experiments: Seq[modeldb.Experiment] = this.experiments,
    experimentRuns: Seq[modeldb.ExperimentRun] = this.experimentRuns,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): ProjectExperimentsAndRuns =
    new Immutable(
      projId,
      experiments,
      experimentRuns,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[ProjectExperimentsAndRuns]

  private def _equals(x: ProjectExperimentsAndRuns, y: ProjectExperimentsAndRuns): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator) &&
      x._passthroughFields == y._passthroughFields

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[ProjectExperimentsAndRuns])

  override def hashCode: Int = {
    var hash = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    hash
  }

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.projId
    case 1 => this.experiments
    case 2 => this.experimentRuns
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "ProjectExperimentsAndRuns"

  def _codec: ValidatingThriftStructCodec3[ProjectExperimentsAndRuns] = ProjectExperimentsAndRuns
}

