/**
 * Generated by Scrooge
 *   version: 18.10.0
 *   rev: dda071e1412b53f4bfdebc19e474f584e475d475
 *   built at: 20181018-174244
 */
package modeldb

import com.twitter.io.Buf
import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob,
  ThriftException,
  ThriftStruct,
  ThriftStructCodec3,
  ThriftStructFieldInfo,
  ThriftStructMetaData,
  ThriftUtil,
  ValidatingThriftStruct,
  ValidatingThriftStructCodec3
}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport, TIOStreamTransport}
import java.io.ByteArrayInputStream
import java.nio.ByteBuffer
import java.util.Arrays
import java.util.concurrent.atomic.AtomicInteger
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object RandomSplitEventResponse extends ValidatingThriftStructCodec3[RandomSplitEventResponse] {
  val NoPassthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty[Short, TFieldBlob]
  val Struct: TStruct = new TStruct("RandomSplitEventResponse")
  val OldDataFrameIdField: TField = new TField("oldDataFrameId", TType.I32, 1)
  val OldDataFrameIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]
  val SplitIdsField: TField = new TField("splitIds", TType.LIST, 2)
  val SplitIdsFieldManifest: Manifest[Seq[Int]] = implicitly[Manifest[Seq[Int]]]
  val SplitEventIdField: TField = new TField("splitEventId", TType.I32, 3)
  val SplitEventIdFieldManifest: Manifest[Int] = implicitly[Manifest[Int]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      OldDataFrameIdField,
      false,
      false,
      OldDataFrameIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      SplitIdsField,
      false,
      false,
      SplitIdsFieldManifest,
      _root_.scala.None,
      _root_.scala.Some(implicitly[Manifest[Int]]),
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    ),
    new ThriftStructFieldInfo(
      SplitEventIdField,
      false,
      false,
      SplitEventIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String],
      None
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: RandomSplitEventResponse): Unit = {
  }

  /**
   * Checks that the struct is a valid as a new instance. If there are any missing required or
   * construction required fields, return a non-empty list.
   */
  def validateNewInstance(item: RandomSplitEventResponse): scala.Seq[com.twitter.scrooge.validation.Issue] = {
    val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]

    buf ++= validateField(item.oldDataFrameId)
    buf ++= validateField(item.splitIds)
    buf ++= validateField(item.splitEventId)
    buf.toList
  }

  def withoutPassthroughFields(original: RandomSplitEventResponse): RandomSplitEventResponse =
    new Immutable(
      oldDataFrameId =
        {
          val field = original.oldDataFrameId
          field
        },
      splitIds =
        {
          val field = original.splitIds
          field.map { field =>
            field
          }
        },
      splitEventId =
        {
          val field = original.splitEventId
          field
        }
    )

  override def encode(_item: RandomSplitEventResponse, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }


  private[this] def lazyDecode(_iprot: LazyTProtocol): RandomSplitEventResponse = {

    var oldDataFrameId: Int = 0
    var splitIds: Seq[Int] = Seq[Int]()
    var splitEventId: Int = 0

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                oldDataFrameId = readOldDataFrameIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'oldDataFrameId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.LIST =>
    
                splitIds = readSplitIdsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.LIST
                throw new TProtocolException(
                  "Received wrong type for field 'splitIds' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
    
                splitEventId = readSplitEventIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'splitEventId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      oldDataFrameId,
      splitIds,
      splitEventId,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): RandomSplitEventResponse =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[modeldb] def eagerDecode(_iprot: TProtocol): RandomSplitEventResponse = {
    var oldDataFrameId: Int = 0
    var splitIds: Seq[Int] = Seq[Int]()
    var splitEventId: Int = 0
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                oldDataFrameId = readOldDataFrameIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'oldDataFrameId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.LIST =>
                splitIds = readSplitIdsValue(_iprot)
              case _actualType =>
                val _expectedType = TType.LIST
                throw new TProtocolException(
                  "Received wrong type for field 'splitIds' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 =>
                splitEventId = readSplitEventIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'splitEventId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      oldDataFrameId,
      splitIds,
      splitEventId,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    oldDataFrameId: Int,
    splitIds: Seq[Int] = Seq[Int](),
    splitEventId: Int
  ): RandomSplitEventResponse =
    new Immutable(
      oldDataFrameId,
      splitIds,
      splitEventId
    )

  def unapply(_item: RandomSplitEventResponse): _root_.scala.Option[_root_.scala.Tuple3[Int, Seq[Int], Int]] = _root_.scala.Some(_item.toTuple)


  @inline private[modeldb] def readOldDataFrameIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeOldDataFrameIdField(oldDataFrameId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(OldDataFrameIdField)
    writeOldDataFrameIdValue(oldDataFrameId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeOldDataFrameIdValue(oldDataFrameId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(oldDataFrameId_item)
  }

  @inline private[modeldb] def readSplitIdsValue(_iprot: TProtocol): Seq[Int] = {
    val _list = _iprot.readListBegin()
    if (_list.size == 0) {
      _iprot.readListEnd()
      Nil
    } else {
      val _rv = new mutable$ArrayBuffer[Int](_list.size)
      var _i = 0
      while (_i < _list.size) {
        _rv += {
          _iprot.readI32()
        }
        _i += 1
      }
      _iprot.readListEnd()
      _rv
    }
  }

  @inline private def writeSplitIdsField(splitIds_item: Seq[Int], _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(SplitIdsField)
    writeSplitIdsValue(splitIds_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeSplitIdsValue(splitIds_item: Seq[Int], _oprot: TProtocol): Unit = {
    _oprot.writeListBegin(new TList(TType.I32, splitIds_item.size))
    splitIds_item match {
      case _: IndexedSeq[_] =>
        var _i = 0
        val _size = splitIds_item.size
        while (_i < _size) {
          val splitIds_item_element = splitIds_item(_i)
          _oprot.writeI32(splitIds_item_element)
          _i += 1
        }
      case _ =>
        splitIds_item.foreach { splitIds_item_element =>
          _oprot.writeI32(splitIds_item_element)
        }
    }
    _oprot.writeListEnd()
  }

  @inline private[modeldb] def readSplitEventIdValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeSplitEventIdField(splitEventId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(SplitEventIdField)
    writeSplitEventIdValue(splitEventId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeSplitEventIdValue(splitEventId_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(splitEventId_item)
  }


  object Immutable extends ThriftStructCodec3[RandomSplitEventResponse] {
    override def encode(_item: RandomSplitEventResponse, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): RandomSplitEventResponse = RandomSplitEventResponse.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[RandomSplitEventResponse] = RandomSplitEventResponse.metaData
  }

  /**
   * The default read-only implementation of RandomSplitEventResponse.  You typically should not need to
   * directly reference this class; instead, use the RandomSplitEventResponse.apply method to construct
   * new instances.
   */
  class Immutable(
      val oldDataFrameId: Int,
      val splitIds: Seq[Int],
      val splitEventId: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends RandomSplitEventResponse {
    def this(
      oldDataFrameId: Int,
      splitIds: Seq[Int] = Seq[Int](),
      splitEventId: Int
    ) = this(
      oldDataFrameId,
      splitIds,
      splitEventId,
      Map.empty[Short, TFieldBlob]
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val oldDataFrameId: Int,
      val splitIds: Seq[Int],
      val splitEventId: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends RandomSplitEventResponse {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the RandomSplitEventResponse trait with additional state or
   * behavior and implement the read-only methods from RandomSplitEventResponse using an underlying
   * instance.
   */
  trait Proxy extends RandomSplitEventResponse {
    protected def _underlying_RandomSplitEventResponse: RandomSplitEventResponse
    override def oldDataFrameId: Int = _underlying_RandomSplitEventResponse.oldDataFrameId
    override def splitIds: Seq[Int] = _underlying_RandomSplitEventResponse.splitIds
    override def splitEventId: Int = _underlying_RandomSplitEventResponse.splitEventId
    override def _passthroughFields: immutable$Map[Short, TFieldBlob] = _underlying_RandomSplitEventResponse._passthroughFields
  }
}

/**
 * Prefer the companion object's [[modeldb.RandomSplitEventResponse.apply]]
 * for construction if you don't need to specify passthrough fields.
 */
trait RandomSplitEventResponse
  extends ThriftStruct
  with _root_.scala.Product3[Int, Seq[Int], Int]
  with ValidatingThriftStruct[RandomSplitEventResponse]
  with java.io.Serializable
{
  import RandomSplitEventResponse._

  def oldDataFrameId: Int
  def splitIds: Seq[Int]
  def splitEventId: Int

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1: Int = oldDataFrameId
  def _2: Seq[Int] = splitIds
  def _3: Int = splitEventId

  def toTuple: _root_.scala.Tuple3[Int, Seq[Int], Int] = {
    (
      oldDataFrameId,
      splitIds,
      splitEventId
    )
  }


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeOldDataFrameIdValue(oldDataFrameId, _oprot)
                _root_.scala.Some(RandomSplitEventResponse.OldDataFrameIdField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (splitIds ne null) {
                writeSplitIdsValue(splitIds, _oprot)
                _root_.scala.Some(RandomSplitEventResponse.SplitIdsField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (true) {
                writeSplitEventIdValue(splitEventId, _oprot)
                _root_.scala.Some(RandomSplitEventResponse.SplitEventIdField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            _root_.scala.Some(TFieldBlob(_field, Buf.ByteArray.Owned(_buff.getArray())))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): RandomSplitEventResponse = {
    var oldDataFrameId: Int = this.oldDataFrameId
    var splitIds: Seq[Int] = this.splitIds
    var splitEventId: Int = this.splitEventId
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        oldDataFrameId = readOldDataFrameIdValue(_blob.read)
      case 2 =>
        splitIds = readSplitIdsValue(_blob.read)
      case 3 =>
        splitEventId = readSplitEventIdValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      oldDataFrameId,
      splitIds,
      splitEventId,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): RandomSplitEventResponse = {
    var oldDataFrameId: Int = this.oldDataFrameId
    var splitIds: Seq[Int] = this.splitIds
    var splitEventId: Int = this.splitEventId

    _fieldId match {
      case 1 =>
        oldDataFrameId = 0
      case 2 =>
        splitIds = Seq[Int]()
      case 3 =>
        splitEventId = 0
      case _ =>
    }
    new Immutable(
      oldDataFrameId,
      splitIds,
      splitEventId,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetOldDataFrameId: RandomSplitEventResponse = unsetField(1)

  def unsetSplitIds: RandomSplitEventResponse = unsetField(2)

  def unsetSplitEventId: RandomSplitEventResponse = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    RandomSplitEventResponse.validate(this)
    _oprot.writeStructBegin(Struct)
    writeOldDataFrameIdField(oldDataFrameId, _oprot)
    if (splitIds ne null) writeSplitIdsField(splitIds, _oprot)
    writeSplitEventIdField(splitEventId, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    oldDataFrameId: Int = this.oldDataFrameId,
    splitIds: Seq[Int] = this.splitIds,
    splitEventId: Int = this.splitEventId,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): RandomSplitEventResponse =
    new Immutable(
      oldDataFrameId,
      splitIds,
      splitEventId,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[RandomSplitEventResponse]

  private def _equals(x: RandomSplitEventResponse, y: RandomSplitEventResponse): Boolean =
      x.productArity == y.productArity &&
      x.productIterator.sameElements(y.productIterator) &&
      x._passthroughFields == y._passthroughFields

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _equals(this, other.asInstanceOf[RandomSplitEventResponse])

  override def hashCode: Int = {
    var hash = _root_.scala.runtime.ScalaRunTime._hashCode(this)
    hash
  }

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.oldDataFrameId
    case 1 => this.splitIds
    case 2 => this.splitEventId
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "RandomSplitEventResponse"

  def _codec: ValidatingThriftStructCodec3[RandomSplitEventResponse] = RandomSplitEventResponse
}

